---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Simple device shadow API"
basePath: "/things"
paths:
  /{thingName}/shadow:
    get:
      description: "Gets the thing shadow for the specified thing."
      operationId: "getThingShadow"
      parameters:
      - name: "thingName"
        in: "path"
        description: "thing name"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResponseStateDocument"
      x-swagger-router-controller: "Default"
    post:
      description: "Updates the thing shadow for the specified thing."
      operationId: "updateThingShadow"
      parameters:
      - name: "thingName"
        in: "path"
        description: "thing name"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/RequestStateDocument"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResponseStateDocument"
      x-swagger-router-controller: "Default"
definitions:
  RequestStateDocument:
    type: "object"
    properties:
      state:
        $ref: "#/definitions/RequestStateDocument_state"
  ResponseStateDocument:
    type: "object"
    properties:
      state:
        $ref: "#/definitions/ResponseStateDocument_state"
      metadata:
        $ref: "#/definitions/ResponseStateDocument_metadata"
  Timestamp:
    type: "object"
    properties:
      timestamp:
        type: "integer"
  RequestStateDocument_state:
    properties:
      desired:
        type: "object"
        properties: {}
      reported:
        type: "object"
        properties: {}
  ResponseStateDocument_state:
    properties:
      desired:
        type: "object"
        properties: {}
      reported:
        type: "object"
        properties: {}
      delta:
        type: "object"
        properties: {}
  ResponseStateDocument_metadata:
    properties:
      desired:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/Timestamp"
      reported:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/Timestamp"
